"""Runnable encrypted Home Credit job definitions."""

from __future__ import annotations

from typing import Any


JOB_TYPES: dict[str, dict[str, Any]] = {
    "home_credit_numeric_summary": {
        "label": "Home Credit Numeric Summary",
        "family": "Home Credit",
        "stage": "Application-train aggregate",
        "scheme": "CKKS",
        "binary": "server_numeric_summary",
        "description": "Packed encrypted sums for selected Home Credit numeric columns.",
        "required": ["crypto_context.bin", "eval_sum_keys.bin", "column_manifest.csv", "columns/"],
        "client_requirements": [
            "Use application_train.csv as the first Home Credit source table.",
            "Rows with null/invalid selected numeric fields removed or imputed before encryption.",
            "Numeric columns such as AMT_CREDIT, AMT_INCOME_TOTAL, AMT_ANNUITY, EXT_SOURCE_1/2/3, and DAYS_BIRTH packed into encrypted chunks.",
            "No raw CSV, plaintext prepared CSV, SK_ID-level plaintext joins, secret key, or decrypted report in the upload.",
            "Manifest rows must point to ciphertext files under columns/.",
        ],
        "server_returns": ["numeric_summary/summary_manifest.csv", "numeric_summary/sums/*.bin"],
        "command": [
            "--context",
            "crypto_context.bin",
            "--eval-sum-keys",
            "eval_sum_keys.bin",
            "--manifest",
            "column_manifest.csv",
            "--input-dir",
            "columns",
            "--output-dir",
            "output/numeric_summary",
        ],
    },
    "home_credit_category_eda": {
        "label": "Category Default-Rate EDA",
        "family": "Home Credit",
        "stage": "Category-risk EDA",
        "scheme": "CKKS",
        "binary": "server_home_credit_aggregate",
        "description": "Encrypted applicant counts, default counts, and amount sums by one-hot Home Credit category buckets.",
        "required": ["crypto_context.bin", "eval_sum_keys.bin", "eval_mult_keys.bin", "aggregate_manifest.csv", "vectors/"],
        "client_requirements": [
            "Encode categories such as NAME_INCOME_TYPE, OCCUPATION_TYPE, NAME_EDUCATION_TYPE, and ORGANIZATION_TYPE as one-hot encrypted masks.",
            "Map null category values into an explicit NULL_OR_UNKNOWN bucket before encryption.",
            "Encrypt TARGET as a 0/1 default mask when target-conditioned reports are requested.",
            "Encrypt numeric amount vectors such as AMT_CREDIT, AMT_INCOME_TOTAL, and AMT_ANNUITY for grouped sums.",
            "No raw strings, raw CSV, plaintext SK_ID joins, or secret keys in the upload.",
        ],
        "server_returns": ["category_eda/aggregate_summary_manifest.csv", "category_eda/aggregates/*.bin"],
        "command": [
            "--context",
            "crypto_context.bin",
            "--eval-sum-keys",
            "eval_sum_keys.bin",
            "--eval-mult-keys",
            "eval_mult_keys.bin",
            "--manifest",
            "aggregate_manifest.csv",
            "--input-dir",
            "vectors",
            "--output-dir",
            "output/category_eda",
            "--analysis-filter",
            "literal:category",
        ],
    },
    "home_credit_bucket_eda": {
        "label": "Age / EXT_SOURCE Bucket EDA",
        "family": "Home Credit",
        "stage": "Bucket-risk EDA",
        "scheme": "CKKS",
        "binary": "server_home_credit_aggregate",
        "description": "Encrypted default-rate tables for age bins, DAYS_EMPLOYED anomaly, and EXT_SOURCE score buckets.",
        "required": ["crypto_context.bin", "eval_sum_keys.bin", "eval_mult_keys.bin", "aggregate_manifest.csv", "vectors/"],
        "client_requirements": [
            "Convert DAYS_BIRTH to positive age years and bucket client-side.",
            "Encode DAYS_EMPLOYED == 365243 as an explicit anomaly mask before encryption.",
            "Bucket EXT_SOURCE_1/2/3 after null handling or explicit null bucket creation.",
            "Encrypt bucket masks and TARGET mask; server only aggregates encrypted masks.",
        ],
        "server_returns": ["bucket_eda/aggregate_summary_manifest.csv", "bucket_eda/aggregates/*.bin"],
        "command": [
            "--context",
            "crypto_context.bin",
            "--eval-sum-keys",
            "eval_sum_keys.bin",
            "--eval-mult-keys",
            "eval_mult_keys.bin",
            "--manifest",
            "aggregate_manifest.csv",
            "--input-dir",
            "vectors",
            "--output-dir",
            "output/bucket_eda",
            "--analysis-filter",
            "literal:bucket",
        ],
    },
    "home_credit_domain_ratio_eda": {
        "label": "Domain Ratio EDA",
        "family": "Home Credit",
        "stage": "Financial-ratio EDA",
        "scheme": "CKKS",
        "binary": "server_home_credit_aggregate",
        "description": "Encrypted aggregate tables for CREDIT_INCOME_PERCENT, ANNUITY_INCOME_PERCENT, CREDIT_TERM, and DAYS_EMPLOYED_PERCENT buckets.",
        "required": ["crypto_context.bin", "eval_sum_keys.bin", "eval_mult_keys.bin", "aggregate_manifest.csv", "vectors/"],
        "client_requirements": [
            "Client computes domain ratios from application_train numeric columns before encryption.",
            "Handle division by zero/nulls client-side with explicit invalid/null buckets.",
            "Encrypt ratio bucket masks and TARGET mask for server-side aggregate counts.",
            "Raw financial values and secret keys stay on the client.",
        ],
        "server_returns": ["ratio_eda/aggregate_summary_manifest.csv", "ratio_eda/aggregates/*.bin"],
        "command": [
            "--context",
            "crypto_context.bin",
            "--eval-sum-keys",
            "eval_sum_keys.bin",
            "--eval-mult-keys",
            "eval_mult_keys.bin",
            "--manifest",
            "aggregate_manifest.csv",
            "--input-dir",
            "vectors",
            "--output-dir",
            "output/ratio_eda",
            "--analysis-filter",
            "literal:ratio",
        ],
    },
    "home_credit_linear_score": {
        "label": "Linear ML Score",
        "family": "Home Credit",
        "stage": "Encrypted inference",
        "scheme": "CKKS",
        "binary": "server_linear_score",
        "description": "Encrypted CKKS weighted-sum inference for a small exported Home Credit linear/logistic model.",
        "required": ["crypto_context.bin", "score_manifest.csv", "score_features/"],
        "client_requirements": [
            "Train/export a small linear model in plaintext, or use the demo policy model for plumbing only.",
            "Prepare scaled numeric feature vectors client-side.",
            "Encrypt feature vectors; server receives only encrypted features and plaintext weights.",
            "Server returns encrypted score chunks; client decrypts and optionally applies sigmoid.",
        ],
        "server_returns": ["linear_score/score_summary_manifest.csv", "linear_score/scores/*.bin"],
        "command": [
            "--context",
            "crypto_context.bin",
            "--manifest",
            "score_manifest.csv",
            "--input-dir",
            "score_features",
            "--output-dir",
            "output/linear_score",
        ],
    },
}


def public_job_types() -> dict[str, dict[str, Any]]:
    return {
        key: {
            "label": value["label"],
            "family": value.get("family", ""),
            "stage": value.get("stage", ""),
            "scheme": value["scheme"],
            "description": value["description"],
            "required": value["required"],
            "client_requirements": value.get("client_requirements", []),
            "server_returns": value.get("server_returns", []),
            "disabled": bool(value.get("disabled")),
        }
        for key, value in JOB_TYPES.items()
    }

